export const menuItems = [
    { name: 'Espresso', price: 75, category: 'classic' },
    { name: 'Americano', price: 85, category: 'classic' },
    { name: 'Macchiato', price: 82, category: 'classic' },
    { name: 'Cortado', price: 90, category: 'classic' },
    { name: 'Cappuccino', price: 100, category: 'classic' },
    { name: 'Flat White', price: 105, category: 'classic' },
    { name: 'Latte', price: 118, category: 'classic' },
    { name: 'Affogato', price: 110, category: 'classic' },
    { name: 'Turkish Coffee', price: 75, category: 'classic' },
    { name: 'Classic Shaken Espresso', price: 135, category: 'classic' },

    { name: 'V60', price: 175, category: 'drip' },
    { name: 'Chemex', price: 195, category: 'drip' },
    { name: 'Aeropress', price: 175, category: 'drip' },
    { name: 'Siphon', price: 200, category: 'drip' },

    { name: 'Caramel Macchiato', price: 130, category: 'flavoured' },
    { name: 'Spanish Latte', price: 145, category: 'flavoured' },
    { name: 'Salted Caramel Latte', price: 155, category: 'flavoured' },
    { name: 'Mocha (White/Dark)', price: 135, category: 'flavoured' },
    { name: 'Cinnamon Latte', price: 155, category: 'flavoured' },
    { name: 'Pistachio Latte', price: 190, category: 'flavoured' },
    { name: 'Shaken Espresso', price: 150, category: 'flavoured' },

    { name: 'Classic Matcha Latte', price: 140, category: 'matcha' },
    { name: 'Honey Matcha Latte', price: 150, category: 'matcha' },
    { name: 'Vanilla Matcha Latte', price: 155, category: 'matcha' },
    { name: 'Hazelnut Matcha Latte', price: 155, category: 'matcha' },
    { name: 'Mango Matcha', price: 155, category: 'matcha' },
    { name: 'Spanish Matcha', price: 165, category: 'matcha' },
    { name: 'Blueberry Matcha', price: 165, category: 'matcha' },
    { name: 'Strawberry Matcha', price: 165, category: 'matcha' },
    { name: 'White Chocolate Matcha', price: 165, category: 'matcha' },

    { name: 'Hot Chocolate Classic', price: 150, category: 'hot' },
    { name: 'Marshmallow Hot Chocolate', price: 175, category: 'hot' },
    { name: 'White Hot Chocolate', price: 160, category: 'hot' },
    { name: 'Mastic Marshmallow', price: 190, category: 'hot' },
    { name: 'English Tea', price: 50, category: 'hot' },
    { name: 'Flavoured Tea', price: 60, category: 'hot' },

    { name: 'Milkshake', price: 135, category: 'refreshers' },
    { name: 'Milkshake (Espresso)', price: 175, category: 'refreshers' },
    { name: 'Fresh Juice', price: 100, category: 'refreshers' },
    { name: 'Classic Mojito', price: 100, category: 'refreshers' },
    { name: 'Flavoured Mojito', price: 130, category: 'refreshers' },
    { name: 'Sweet & Sour Mojito', price: 145, category: 'refreshers' },
    { name: 'Ice Tea', price: 120, category: 'refreshers' },
    { name: 'Tropical Hibiscus', price: 150, category: 'refreshers' },
    { name: 'Redbull', price: 110, category: 'refreshers' },
    { name: 'Soft Drinks', price: 45, category: 'refreshers' },

    { name: 'Triple Cheese Club Sandwich', price: 140, category: 'sandwiches' },
    { name: 'Grilled Halloumi Sandwich', price: 130, category: 'sandwiches' },
    { name: 'Smoked Chicken Sandwich', price: 140, category: 'sandwiches' },
    { name: 'Moroccan Chicken Sandwich', price: 175, category: 'sandwiches' },
    { name: 'Roasted Beef Sandwich', price: 200, category: 'sandwiches' },
    { name: 'Mozzarella Chicken Panini', price: 170, category: 'sandwiches' },
    { name: 'Tandoori Chicken Panini', price: 170, category: 'sandwiches' },
    { name: 'Barbecue Chicken', price: 160, category: 'sandwiches' },
    { name: 'Roasted Beef Caramelized Onion Bagel', price: 210, category: 'sandwiches' },
    { name: 'Chicken Honey Mustard Pretzel', price: 175, category: 'sandwiches' },
    { name: 'Bacon Turkey', price: 180, category: 'sandwiches' },
    { name: 'Tuna Sandwich', price: 180, category: 'sandwiches' },
    { name: 'Croissant Mix Cheese', price: 145, category: 'sandwiches' },
    { name: 'Croissant Kiri Turkey', price: 150, category: 'sandwiches' },
    { name: 'Croissant Plain', price: 95, category: 'sandwiches' },

    { name: 'Brownies', price: 125, category: 'desserts' },
    { name: 'Honey Cake', price: 160, category: 'desserts' },
    { name: 'Carrot Cake', price: 170, category: 'desserts' },
    { name: 'Red Velvet Cake', price: 150, category: 'desserts' },
    { name: 'Cookies', price: 85, category: 'desserts' },
    { name: 'Chocolate Mousse', price: 150, category: 'desserts' },
    { name: 'Cheese Cake', price: 110, category: 'desserts' },
    { name: 'Cheese Cake Flavor', price: 140, category: 'desserts' },
    { name: 'Lemon Cake', price: 90, category: 'desserts' }
];